### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by osdiab** [matthewp/react-robot#11]
Down to help with this! or to implement it in TypeScript so that it's automatic.

**Comment by matthewp** [comment]
Typings file please and thank you!

**Comment by FranklinChen** [comment]
Is there a volunteer still needed for this issue?

**Comment by osdiab** [comment]
I didn't end up using robot for my current project, so I didn't end up making this - if time frees up i might still contribute it but probably best if someone else volunteers!

**Comment by jackmellis** [comment]
I've just started using robot but I don't think the ts for react-robot/robot is quite right.
```ts
createMachine(
  {
    first: state(transition('next', 'done')),
    done: state(),
  },
);
```
If I try to call `useMachine` with the above I get a typescript error `Argument of type 'Machine<{ name: MachineState; age: MachineState; height: MachineState; done: MachineState; }, unknown, State>' is not assignable to parameter of type 'Machine<{}, {}, string>'`

If I add a context initializer to my machine i.e. `(ctx: any) => ctx` then it fixes it

I think the problem is that createMachine falls back to a context type of `unknown` instead of the default context type of `{}` that `Machine` has.

**Comment by matthewp** [comment]
Thanks for the feedback @jackmellis. I've started using TypeScript more personally so it's possible that I might change Robot to use TypeScript which would help things.. We'll see. I appreciate the feedback.
